language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
after_success:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
