export const  USER_LOGGED_IN = 'USER_LOGGED_IN';
export const  USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const EVENT_CREATED = 'EVENT_CREATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PASSWORD_RESET = 'PASSWORD_RESET';